version: 0.2
phases:
  install:
    commands:
      # Install terraform
      - cd /tmp
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TerraformVersion}/terraform_${TerraformVersion}_linux_amd64.zip
      - echo "${TerraformSha256} terraform.zip" | sha256sum -c --quiet
      - unzip terraform.zip && mv terraform /usr/bin
      # Install terragrunt
      - curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${TerragruntVersion}/terragrunt_linux_amd64
      - echo "${TerragruntSha256} terragrunt" | sha256sum -c --quiet
      - chmod +x terragrunt
      - mv terragrunt /usr/bin
  pre_build:
    commands:
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/environment
      # Create and switch to workspace for target environment
      - terragrunt workspace new ${Environment} || true # Continue if exit code indicates workspace exists already.
      - terragrunt workspace select ${Environment}
      # Apply the changes
      - terragrunt init
      - terragrunt plan -out plan.tf
      - terragrunt apply -auto-approve plan.tf
